CarWashBer/CarWashBer/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarWashBer.Models;
using CarWashBer.Services;
using Microsoft.AspNetCore.Identity;
using CarWashBer.ViewModels;

namespace CarWashBer.Controllers
{
    public class CarsController : Controller
    {
        private IManageCars _manageCars;
        private readonly UserManager<Customer> _userManager;

        public CarsController(IManageCars manageCars,
                              UserManager<Customer> userManager)
        {
            this._manageCars = manageCars;
            this._userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            return View(_manageCars.GetUserCars(user));
        }

        public IActionResult Details(int? id)
        {
            var car = _manageCars.GetCarById(id);
            return View(car);
        }

        public IActionResult Create()
        {
            ViewBag.ListOfBrands = _manageCars.GetCarBrands();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarViewModel carViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                _manageCars.AddCar(user,carViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(carViewModel);
        }

        public IActionResult Edit(int? id)
        {
            ViewBag.ListOfBrands = _manageCars.GetCarBrands();
            var car = _manageCars.GetCarById(id);
            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("CarId,Brand,Model,LicensePlate")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _manageCars.UpdateCar(id, car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        public IActionResult Delete(int? id)
        {
            var car = _manageCars.GetCarById(id);
            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _manageCars.DeleteCarById(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public JsonResult GetModelsList(int id)
        {
            var CarModelsList = new SelectList(_manageCars.GetCarModelsByCarBrandId(id), "CarModelId", "ModelName");
            return Json(CarModelsList);
        }
    }
}

CarWashBer/CarWashBer/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarWashBer.Models;
using CarWashBer.Services;

namespace CarWashBer.Controllers
{
    public class OperationsController : Controller
    {
        private IManageOperations _manageOperations;

        public OperationsController(IManageOperations manageOperations)
        {
            _manageOperations = manageOperations;
        }

        public IActionResult Index()
        {
            return View(_manageOperations.GetOperations());
        }

        public IActionResult Details(int? id)
        {
            var operation = _manageOperations.GetOperationById(id);
            return View(operation);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("OperationId,Name,Cost,TimeSpent,IsChecked")] Operation operation)
        {
            if (ModelState.IsValid)
            {
                _manageOperations.AddOperation(operation);
                return RedirectToAction(nameof(Index));
            }
            return View(operation);
        }

        public IActionResult Edit(int? id)
        {
            var operation = _manageOperations.GetOperationById(id);
            return View(operation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("OperationId,Name,Cost,TimeSpent,IsChecked")] Operation operation)
        {
            if (id != operation.OperationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _manageOperations.UpdateOperation(id, operation);
                return RedirectToAction(nameof(Index));
            }
            return View(operation);
        }

        public IActionResult Delete(int? id)
        {
            var operation = _manageOperations.GetOperationById(id);
            return View(operation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _manageOperations.DeleteOperationById(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

CarWashBer/CarWashBer/Views/Shared/_Layout.cshtml
@inject SignInManager<Customer> signInManager;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWashBer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car Wash</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operations" asp-action="Index">Operations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="CreateRole">Create Roles</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0">
                                        LogOut @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">LogIn</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Car Wash Bercu Adrian
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>